server:
 rootPath: /i/
 applicationConnectors:
 - type: http
   port: 8090
 adminConnectors:
 - type: http
   port: 8091

database:
 driverClass: org.postgresql.Driver 
 user: ${JDBC_DATABASE_USERNAME}
 password: ${JDBC_DATABASE_PASSWORD}
 url: ${JDBC_DATABASE_URL}
 properties:
  charSet: UTF-8
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.hbm2ddl.auto: create
  #hibernate.show_sql: true
 maxWaitForConnection: 1s
 validationQuery: "/* MyApplication Health Check */ SELECT 1"
 minSize: 8
 maxSize: 32
 checkConnectionWhileIdle: false

viewRendererConfiguration:
 .ftl:
  strict_syntax: yes
  whitespace_stripping: yes

